# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Lindsay's Blog
email: aml.lindsay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog about whatever I find interesting. It will probably be mostly programming related, maybe with some games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amlblog.net" # the base hostname & protocol for your site
twitter:
  username: allmanylots
author:
  twitter: allmanylots
twitter_username: allmanylots
github_username: alexanderlindsay

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - .git/

timezone: America/Los_Angeles
paginate: 10

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

gems:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag

emptyArray: []

# Staticman
staticman:
    allowedFields: ['name', 'email', 'url', 'message']
    branch: master
    commitMessage: "Staticman adding comment"
    generatedFields:
        date:
            type: date
            options:
                format: "timestamp-seconds"
    format: yml
    moderation: true
    path: "_data/comments/{options.slug}"
    requiredFields: ['name', 'email', 'message']
    transforms:
        email: 'md5'
    url: https://api.staticman.net/v1/entry/AlexanderLindsay/AlexanderLindsay.github.io/master
